### ISSUE TITLE
Change config & Dockerfile to use Dogecoin software

### ISSUE THREAD

**Issue by patricklodder** [rosetta-dogecoin/rosetta-dogecoin#4]
1) Adapt the config files in `assets/` to reflect Dogecoin  

2) Change the bitcoin build to dogecoin

https://github.com/rosetta-dogecoin/rosetta-dogecoin/blob/e0e70cacd9367e726cb5097ee98d5e6e831ca1b1/Dockerfile#L22-L37

can likely be replaced by a download of the 64-bit binaries from 
https://github.com/dogecoin/dogecoin/releases/tag/v1.14.3 and then just take
out the dogecoind executable. and put it in /app/dogecoind

**Comment by xanimo** [comment]
I can do this one too.

**Comment by xanimo** [comment]
A couple quick questions regarding dependencies:

I understand that on line 33 we're passing --disable-wallet and dogecoin requires libdb5.1-dev libdb5.1++-dev which are required for Berkeley DB instead of libdb++-dev however I ran into this issue several times when compiling full nodes that those packages have no installation candidate.  Will libdb++-dev fulfill those requirements or is this is non issue.

I also noticed dogecoin is not using libcurl4-openssl-dev as is in this source.  Should I include or omit this dep?  

And finally one more question is should I include the CXXFLAGS (CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768") in the Dockerfile?

**Comment by patricklodder** [comment]
If you take the precompiled dogecoind, you don't need any of the compiler or *-dev dependencies. You just take wget and then you use that to `wget https://github.com/dogecoin/dogecoin/releases/download/v1.14.3/dogecoin-1.14.3-x86_64-linux-gnu.tar.gz` - those have gone through gitian builds so they can be reproduced.

If this can work with precompiled binaries then this would definitely be the best way. You can check the shasum of the archive too then and don't need to worry about supply chain attacks or library support.

**Comment by xanimo** [comment]
Aw yes, I didn't consider that.  I did get it to successfully compile into an image but it breaks due to broken modules within main.go.  Specific error is "FATAL main src/main.go:133 unable to load configuration {"error": "MODE must be populated"}".

I'll do a rewrite with the precompiled binary and then move onto the aforementioned issue.

**Comment by patricklodder** [comment]
The fatal is caused by missing environment variables. This works for me right now:

```
MODE=OFFLINE NETWORK=TESTNET PORT=8080 ./dogecoin-rosetta -d
```

Where:

- `MODE` can be `OFFLINE` or `ONLINE`
- `NETWORK` can be `TESTNET` or `MAINNET`
- `PORT` is the port that the rosetta interface listens on.

**Comment by xanimo** [comment]
Awesome!  I think you're beating me.  🏆

A question about that Dockerfile and using the precompiled binary, if we were to compile normally there is the line where it moves src/bitcoind to app/rosetta-bitcoin.

1) Is bitcoind equal to bitcoind.cpp in the Bitcoin source code or is that a binary compiled that ends up in src/bitcoind after build?

2) When I've traditionally extracted binaries I usually put them in usr/local usr/local/bin on Debian system.  I am wondering what files need to be moved to app/rosetta-dogecoin after gz extraction?

And thanks for helping me learn!

**Comment by patricklodder** [comment]
> 1. Is bitcoind equal to bitcoind.cpp in the Bitcoin source code or is that a binary compiled that ends up in src/bitcoind after build?

that binary is what is being compiled (and linked) through all these source files

> 2. When I've traditionally extracted binaries I usually put them in usr/local usr/local/bin on Debian system. I am wondering what files need to be moved to app/rosetta-dogecoin after gz extraction?

You should only need the binary `dogecoind` - it's statically linked and you shouldn't need anything else.

**Comment by xanimo** [comment]
I am having some trouble successfully starting my container.  It successfully extracts dogecoind to app/dogecoind and builds without an issue.  I try to pass flags:

docker run -d --rm --ulimit "nofile=100000:100000" -v "$(pwd)/bitcoin-data:/data" -e "MODE=ONLINE" -e "NETWORK=TESTNET" -e "PORT=8080" -p 8080:8080 -p 18333:18333 rosetta-dogecoin:latest

This runs and I get this as an example output: 7a0ec5ef573ced0b70f0c720a8320aa145ce40d11172bc30cb2e77e247325ae2

But when I try to look up the logs:

docker logs --tail 100 rosetta-dogecoin:latest

Error: No such container: rosetta-dogecoin

I've also used the sha256 of the container instead of rosetta-dogecoin:latest and encounter the same issue.

Would it be possible for anyone to fork my repo and replicate and or just have a look over my code?  I am not sure if this is par for the course since other dependent components are not configured properly or if my build process is flawed.  Thanks!

**Comment by patricklodder** [comment]
`rosetta-dogecoin:latest` is the image name.

The container name is the "example output": `7a0ec5ef573ced0b70f0c720a8320aa145ce40d11172bc30cb2e77e247325ae2`

you can just tell it something like `7a` though, i.e.: `docker logs --tail 100 7a` should work

**Comment by xanimo** [comment]
![Screenshot (349)](https://user-images.githubusercontent.com/31856436/111841767-b7de6780-88bb-11eb-94e0-c2ed698488de.jpg)

Ok, I'm still unable to get the logs but I did happen to get this!

**Comment by patricklodder** [comment]
Those are the logs! I would recommend PR-ing this, and I'll review your code, then we merge and it will be properly broken but that's fine for now. Then we can start fixing configuration as issues pop up and do quick cycles.

**Comment by xanimo** [comment]
Sounds good, submitted.
